controller_list:
  - name: fake_manipulatorA_axis_controller
    joints:
      - cartA_joint
      - robotA_joint_1
      - robotA_joint_2
      - robotA_joint_3
      - robotA_joint_4
      - robotA_joint_5
      - robotA_joint_6
  - name: fake_manipulatorB_axis_controller
    joints:
      - cartB_joint
      - robotB_joint_1
      - robotB_joint_2
      - robotB_joint_3
      - robotB_joint_4
      - robotB_joint_5
      - robotB_joint_6
  - name: fake_manipulatorA_controller
    joints:
      - cartA_joint
      - cartB_joint
      - robotB_joint_1
      - robotB_joint_2
      - robotB_joint_3
      - robotB_joint_4
      - robotB_joint_5
      - robotB_joint_6
  - name: fake_manipulatorB_controller
    joints:
      - robotB_joint_1
      - robotB_joint_2
      - robotB_joint_3
      - robotB_joint_4
      - robotB_joint_5
      - robotB_joint_6